/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#ffda49',
        'background': '#f5fcef',
        'on-surface-variant': '#42493e',
        'tertiary-fixed': '#66ff8e',
        'on-error': '#ffffff',
        'on-primary-container': '#9dd090',
        'secondary': '#705d00',
        'on-primary-fixed-variant': '#23501e',
        'on-tertiary-fixed': '#002109',
        'surface-tint': '#3b6934',
        'surface-dim': '#d5dcd0',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#a1d494',
        'surface-container': '#e9f0e4',
        'primary-container': '#2d5a27',
        'on-primary-fixed': '#002201',
        'tertiary-fixed-dim': '#3de273',
        'on-secondary-fixed-variant': '#554500',
        'on-tertiary-container': '#37de6f',
        'secondary-fixed': '#ffe174',
        'inverse-on-surface': '#ecf3e6',
        'on-secondary-container': '#735f00',
        'inverse-primary': '#a1d494',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface': '#f5fcef',
        'on-background': '#171d16',
        'surface-variant': '#dee5d8',
        'on-tertiary-fixed-variant': '#005322',
        'error-container': '#ffdad6',
        'outline-variant': '#c2c9bb',
        'surface-container-high': '#e3eade',
        'surface-container-low': '#eff6e9',
        'secondary-fixed-dim': '#e7c433',
        'on-error-container': '#93000a',
        'outline': '#72796e',
        'inverse-surface': '#2b322a',
        'error': '#ba1a1a',
        'on-surface': '#171d16',
        'on-secondary-fixed': '#221b00',
        'surface-container-highest': '#dee5d8',
        'tertiary-container': '#005d27',
        'primary': '#154212',
        'primary-fixed': '#bcf0ae',
        'surface-bright': '#f5fcef',
        'tertiary': '#00431a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
