/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d9dadc',
        'on-primary-fixed-variant': '#6b3b00',
        'primary-container': '#2d1600',
        'primary-fixed-dim': '#ffb875',
        'on-tertiary-fixed-variant': '#484644',
        'tertiary-fixed-dim': '#cac6c2',
        'on-primary': '#ffffff',
        'secondary-container': '#e2dfe0',
        'inverse-surface': '#2f3132',
        'on-primary-container': '#c26f00',
        'outline': '#76777b',
        'error': '#ba1a1a',
        'background': '#f9f9fb',
        'surface-bright': '#f9f9fb',
        'surface-container-high': '#e8e8ea',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdcc0',
        'tertiary-container': '#1c1b19',
        'error-container': '#ffdad6',
        'surface-container-highest': '#e2e2e4',
        'on-error': '#ffffff',
        'tertiary': '#000000',
        'surface-tint': '#8d4f00',
        'outline-variant': '#c7c6ca',
        'on-surface': '#1a1c1d',
        'surface': '#f9f9fb',
        'inverse-on-surface': '#f0f0f2',
        'secondary-fixed': '#e5e2e3',
        'tertiary-fixed': '#e6e2de',
        'on-tertiary-fixed': '#1c1b19',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#2d1600',
        'surface-container': '#eeeef0',
        'on-secondary-container': '#636263',
        'secondary': '#5f5e5f',
        'surface-container-low': '#f3f3f5',
        'inverse-primary': '#ffb875',
        'on-background': '#1a1c1d',
        'secondary-fixed-dim': '#c8c6c7',
        'on-secondary-fixed': '#1b1b1c',
        'surface-variant': '#e2e2e4',
        'primary': '#000000',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#868380',
        'on-surface-variant': '#46474a',
        'on-secondary-fixed-variant': '#474647',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Space Grotesk', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
